plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version "${fabric_loom_version}" apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version "${mod_dev_gradle_version}" apply false
    id "me.modmuss50.mod-publish-plugin" version "${mod_publish_plugin_version}"
}

publishMods {
    file = remapJar.archiveFile
    changelog = new File("${rootProject.projectDir}/changelog.md").text
    type = STABLE

    // CurseForge options used by both Fabric and Forge
    def cfOptions = curseforgeOptions {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "123456"
        minecraftVersions.add("1.20.1")
    }

    // Modrinth options used by both Fabric and Forge
    def mrOptions = modrinthOptions {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "12345678"
        minecraftVersions.add("1.20.1")
    }

    // Fabric specific options for CurseForge
    curseforge("curseforgeFabric") {
        from cfOptions
        file project(":fabric")
        modLoaders.add("fabric")
        displayName = "[Fabric] ${minecraft_version} - ${mod_version}"

        requires {
            slug = "fabric-api"
        }
    }

    // Forge specific options for CurseForge
    curseforge("curseforgeForge") {
        from cfOptions
        file project(":forge")
        modLoaders.add("forge")
        displayName = "[Forge] ${minecraft_version} - ${mod_version}"
    }

    // Fabric specific options for Modrinth
    modrinth("modrinthFabric") {
        from mrOptions
        file project(":fabric")
        modLoaders.add("fabric")
        requires {
            slug = "fabric-api"
        }
    }

    // Forge specific options for Modrinth
    modrinth("modrinthForge") {
        from mrOptions
        file project(":forge")
        modLoaders.add("forge")
    }
}