plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version "${fabric_loom_version}" apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version "${mod_dev_gradle_version}" apply false
    id "me.modmuss50.mod-publish-plugin" version "${mod_publish_plugin_version}"
}