org.gradle.jvmargs=-Xmx8G

# Project Versions
java_version=25
mixin_version=0.8.4
fabric_loom_version=1.17-SNAPSHOT
mod_dev_gradle_version=2.0.140
mod_publish_plugin_version=1.1.0

# Build Jar
minecraft_version=26.2
maximum_minecraft_version=26.2

neo_form_version=26.2-1


# Mod Information

# Changing the mod_id alone will not change it everywhere. There will have to be some manual edits in each loader files in order to change mod id fully
mod_id=lifesteal

mod_name=Lifesteal
mod_version=10.0.7
mod_release_type=Release
mod_base_package=mc.mian
mod_authors=MianReplicate
mod_description=A Minecraft mod where you steal people's hearts hehe.
mod_credits=Jeryn99 (Code)
mod_license=PolyForm Shield License 1.0.0
logo_file=logo.png
repository_url=https://github.com/MianReplicate/Lifesteal
issue_tracker_url=https://github.com/MianReplicate/Lifesteal/issues

# For publishing purposes
curseforge_id=645185
modrinth_id=YX0eip4b

# Common dependencies
indestructible_blocks_version=1.0.5-26.1
common_networking_version=26.2-1.1.0
mixin_extras_version=0.5.3
forge_config_api_port_version=26.2.0

# NeoForge dependencies: https://projects.neoforged.net/
neo_version=26.2.0.1-beta
neo_version_range=[26,)
neo_loader_version_range=[1,)

# Forge dependencies: https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.0
forge_version_range=[65,)
forge_loader_version_range=[65,)
event_bus_version=7.0-beta.15

net.minecraftforge.gradle.merge-source-sets=true

# Fabric dependencies: https://fabricmc.net/develop/
fabric_loader_version=0.16.3
fabric_api_version=0.152.1