org.gradle.jvmargs=-Xmx8G

# Project Versions
java_version=21
mixin_version=0.8.4

# Build Jar
minecraft_version=1.21.11
# Uncomment when parchment is using cross version mappings
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
neo_form_version=1.21.11-20251209.172050
fabric_loom_version=1.15-SNAPSHOT
mod_dev_gradle_version=2.0.140
mod_publish_plugin_version=1.1.0

# Mod Information

# Changing the mod_id alone will not change it everywhere. There will have to be some manual edits in each loader files in order to change mod id fully
mod_id=lifesteal

mod_name=Lifesteal
mod_version=10.0.7
mod_release_type=Release
mod_base_package=mc.mian
mod_authors=MianReplicate
mod_description=A Minecraft mod where you steal people's hearts hehe.
mod_credits=Jeryn99 (Code)
mod_license=PolyForm Shield License 1.0.0
logo_file=logo.png
repository_url=https://github.com/MianReplicate/Lifesteal
issue_tracker_url=https://github.com/MianReplicate/Lifesteal/issues

# For publishing purposes
curseforge_id=645185
modrinth_id=YX0eip4b

# Common dependencies
forge_config_api_port_version=21.11.1
indestructible_blocks_version=1.0.5-1.21.11
common_networking_version=1.0.22-1.21.11
mixin_extras_version=0.4.1

# NeoForge dependencies
neo_version=21.11.38-beta
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Forge dependencies
forge_version=61.1.1
forge_version_range=[61,)
forge_loader_version_range=[61,)
event_bus_version=7.0-beta.15

net.minecraftforge.gradle.merge-source-sets=true

# Fabric dependencies
fabric_loader_version=0.18.1
fabric_api_version=0.141.3