plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.8,8)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

apply from: '../publish.gradle'


minecraft {
    var parchment_version = ""
    if(rootProject.hasProperty('parchment_minecraft_version')) {
        parchment_version += parchment_minecraft_version + "-"
    }
    parchment_version += parchment_mappings_version + "-" + minecraft_version
    println parchment_version
    mappings channel: "parchment", version: parchment_version

    accessTransformer = true

    runs {
        configureEach {
            args "-mixin.config=${mod_id}-common.mixins.json"

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', "${mod_id}"
        }

        register("client") {
            workingDir = file('runs/client')
        }

        register("server") {
            workingDir = file('runs/server')
        }
    }
}

jarJar.register() {
    archiveClassifier = null
}

repositories {
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

minecraft.mavenizer(repositories)

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor "net.minecraftforge:eventbus-validator:${event_bus_version}"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}")

    implementation("mysticdrew:common-networking-forge:${common_networking_version}")
    implementation("mc.mian:indestructible-blocks:forge-${indestructible_blocks_version}")
}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}-common.mixins.json"
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {

        }
    }
}