plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

apply from: '../publish.gradle'

neoForge {
    version = neo_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            jvmArguments = ['-XX:+AllowEnhancedClassRedefinition', "-XX:+AllowRedefinitionToAddDeleteMethods", '-XX:+IgnoreUnrecognizedVMOptions']
        }

        client {
            client()
        }
        data {
            clientData()
            programArguments = ["--all",
                                "--mod", "${mod_id}",
                                "--output", file("src/generated/resources").absolutePath]
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation("mysticdrew:common-networking-neoforge:${common_networking_version}")
    implementation("mc.mian:indestructible_blocks:${indestructible_blocks_version}+${minecraft_version}-neoforge")
    implementation("fuzs.forgeconfigapiport:forgeconfigapiport-neoforge:${forge_config_api_port_version}")
}